"""Domain Pydantic schemas for Explanation Context and Gemini Explanation layer.

Defines schemas for:
- Facts-only ExplanationContext passed to Gemini
- Structured GeminiExplanationResponse schema
"""

from typing import Dict, List, Optional, Any
from pydantic import BaseModel, Field, ConfigDict

from app.recommendation.schema import Recommendation


class ExplanationContext(BaseModel):
    """Facts-only structured payload constructed for downstream Gemini explanation."""
    model_config = ConfigDict(arbitrary_types_allowed=True)

    user_id: str = Field(..., description="Unique account identifier")
    snapshot_time: str = Field(..., description="Point-in-time snapshot timestamp T")
    current_balance: float = Field(..., description="Observed liquid balance in BDT")
    spendable_amount: float = Field(..., description="Calculated safely spendable capacity in BDT")
    protected_amount: float = Field(..., description="Total liquidity protected for obligations and reserve")
    planning_horizon_days: int = Field(30, description="Planning horizon window in days")
    
    expected_inflow: float = Field(..., description="Projected cumulative incoming cash flow")
    expected_outflow: float = Field(..., description="Projected cumulative outgoing cash flow")
    upcoming_commitments: float = Field(..., description="Sum of detected recurring commitment obligations")
    forecasted_minimum_balance: float = Field(..., description="Model-predicted minimum account balance")
    safety_reserve: float = Field(..., description="Adaptive safety reserve buffer in BDT")
    liquidity_state: str = Field(..., description="Categorical liquidity state (HEALTHY, WATCH, PRESSURED)")
    
    recommendations: List[Recommendation] = Field(default_factory=list, description="Prioritized deterministic recommendations")
    scenario: Optional[Dict[str, Any]] = Field(None, description="Hypothetical scenario result details, if applicable")
    limitations: List[str] = Field(
        default_factory=lambda: [
            "Based strictly on observed account activity up to snapshot time T.",
            "Does not include unobserved bank accounts, physical cash, external wallets, or unrecorded financial liabilities."
        ],
        description="Explicit scope limitations and disclaimers"
    )


class GeminiExplanationResponse(BaseModel):
    """Structured response schema returned by Gemini explanation layer (or deterministic fallback)."""
    model_config = ConfigDict(arbitrary_types_allowed=True)

    summary: str = Field(..., description="Concise human-readable summary of Spendable capacity")
    why: List[str] = Field(..., description="Bullet points explaining why Spendable differs from current balance")
    key_factors: List[str] = Field(..., description="Key commitments, forecast dips, or safety reserve factors")
    recommendations: List[str] = Field(..., description="Actionable recommendation highlights")
    scenario_explanation: Optional[str] = Field(None, description="Explanation of hypothetical scenario impact, if applicable")
    disclaimer: str = Field(..., description="Standard responsible AI limitations disclaimer")
    is_fallback: bool = Field(False, description="True if generated by deterministic fallback engine due to API unavailability")
